### ISSUE TITLE
Feature Request - Callback

### ISSUE THREAD

**Issue by Jonathlee** [JoeBonham/jQuery-Full-Width-Image-Slider#1]
Anyway to support callback?

onBegin - slideshow loaded and begin 1st slide
onComplete - each slide ends
onBegin - Before the the next slide appear

This would be great to animate (CSS3 transition) caption on each slide appear and ends before the next slide appear.

**Comment by JoeBonham** [comment]
Good idea! I've just pushed a number of updates that I'd been meaning to do for a while. I added in two events like you suggested, it's probably easiest for you to check out the updated description. If you have any issues with them then just comment here or email me at the address in my profile and I'll be happy to help.

**Comment by Jonathlee** [comment]
Wow, this is great :+1:  gotta Twit this.
